#ifndef _GOC_OKIENKOC_H_
#define _GOC_OKIENKOC_H_

#include "global-inc.h"
#include "global.h"
#include "system.h"
#include "tablica.h"
#include "term.h"
#include "element.h"
#include "ramka.h"
#include "napis.h"
#include "wpis.h"
#include "przycisk.h"
#include "screen.h"
#include "lista.h"
#include "forma.h"
#include "wybor.h"
#include "pasek.h"
#include "procent.h"
#include "maska.h"
#include "plik.h"
#include "hotkey.h"
#include "grupa.h"
#include "slista.h"
#include "plista.h"
#include "maparaw.h"
#include "mapapos.h"
#include "slidebar.h"

#endif // ifndef _GOC_OKIENKOC_H_
